server:
  port: 8080
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:password@lsb2-eureka-server:8080/eureka/
spring:
  cloud:
    config:
      uri: http://lsb2-config-server:8080
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # ========================================================
      - id: imagesService
        uri: lb://lsb2-images
        predicates:
        - Path=/imagesService/**
        filters:
        - RewritePath=/imagesService/(?<segment>.*), /$\{segment}
        - RewritePath=/imagesService, /
        - SaveSession
      - id: images
        uri: lb://lsb2-images
        predicates:
        - Path=/images/**
        filters:
        - SaveSession
      - id: mainCss
        uri: lb://lsb2-images
        predicates:
        - Path=/main.css
        filters:
        - SaveSession
      - id: commentsService
        uri: lb://lsb2-images
        predicates:
        - Path=/comments/**
        filters:
        - SaveSession
    stream:
      bindings:
        input:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        newComments:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: learning-spring-boot-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: learning-spring-boot-chat-user-messages
          group: topic-chatMessages
  rabbitmq:
    host: ${RABBITMQ_HOST:local-rabbitmq}
    port: ${RABBITMG_PORT:5672}
    username: ${RABBITMG_USERNAME:guest}
    password: ${RABBITMG_PASSWORD:guest}
  data:
    mongodb:
      host: ${MONGODB_HOST:local-mongo-server}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB_NAME:lsb2db}

security:
  sessions: always

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
