server:
  port: 8080
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://local-config-server:8080}
eureka:
  instance:
    hostname: local-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/