eureka:
  client:
    serviceUrl:
      defaultZone: http://local-eureka-server:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  
