server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  
