eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  
