server:
  port: 8080
security:
  sessions: never
images:
  commentsUser: user
  commentsPassword: password
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

# tag::secured[]
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:password@lsb2-eureka-server:8080
    instance:
      hostname: lsb2-eureka-server
# end::secured[]

spring:
  cloud:
    config:
      uri: http://lsb2-config-server:8080
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
 
  rabbitmq:
    host: ${RABBITMQ_HOST:local-rabbitmq}
    port: ${RABBITMG_PORT:5672}
    username: ${RABBITMG_USERNAME:guest}
    password: ${RABBITMG_PASSWORD:guest}

  data:
    mongodb:
      host: ${MONGODB_HOST:local-mongo-server:27017}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB_NAME:lsb2db}
 