server:
  port: ${PORT:8080}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
  devtools:
    remote:
      debug:
        local-port: 48200
      secret: thisismysecret
  rabbitmq:
    host: ${RABBITMQ_HOST:local-rabbitmq}
    port: ${RABBITMG_PORT:5672}
    username: ${RABBITMG_USERNAME:guest}
    password: ${RABBITMG_PASSWORD:guest}

  data:
    mongodb:
      host: ${MONGODB_HOST:local-mongo-server}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB_NAME:lsb2db}
