server:
  port: 8200
security:
  sessions: never
images:
  commentsUser: user
  commentsPassword: password
  commentsUrl: http://localhost:9000
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
    function:
      definition: emit
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:localhost}
                port: ${RABBITMQ_PORT:5672}
                username: ${RABBITMQ_USERNAME:guest}
                password: ${RABBITMQ_PASSWORD:guest}
                virtual-host: /
      bindings:
        emit-out-0:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
          binder: rabbit
 
#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMG_PORT:5672}
#    username: ${RABBITMG_USERNAME:guest}
#    password: ${RABBITMG_PASSWORD:guest}

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB_NAME:lsb2db}
 