server:
  port: 9000
security:
  sessions: never
  user:
    password: password

togglz:
  console:
    secured: ${SECURE_TOGGLZ:true}
    enabled: true
    path: /actuator/togglz
    use-management-port: false
    feature-admin-authority: ROLE_ADMIN
  cache:
    enabled: false # Enable feature state caching.
    time-to-live: 0 # The time after which a cache entry will expire.
    time-unit: milliseconds # The time unit as java.util.concurrent.TimeUnit enum name (one of "nanoseconds", "microseconds", "milliseconds", "seconds", "minutes", "hours", "days").
  feature-enums: com.greglturnquist.learningspringboot.comments.MyFeatures
  
#
# details on endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  session:
    store-type: mongodb
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMG_PORT:5672}
    username: ${RABBITMG_USERNAME:guest}
    password: ${RABBITMG_PASSWORD:guest}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB_NAME:lsb2db}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
        output:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
